name: Checkout
on: [push]

jobs:
 
  checkout-and-display-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          git checkout main
          gh repo edit -d "testing repo description"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: List Files After
        run: ls -a