name: Checkout
on: [push]

jobs:
 
  checkout-and-display-files:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      deployments: write

    steps:
      - uses : actions/checkout@v4
        with :
          fetch-depth: 0
      
      - name: Install GH CLI
        uses: dev-hanz-ops/install-gh-cli-action@v0.1.0
        with:
          gh-cli-version: 2.32.0 # optional, see action.yml for current default

      - name: repodescription
        shell: bash
        run: |
          gh repo view --json description | grep -oP '(?<="description":")[^"]*' | grep -oP '[a-zA-Z0-9 ]+' | tee -a log.txt
          echo "repo-description=$(cat log.txt)"
          gh repo edit -d "testing vinay desc"
        env:
         GH_TOKEN: ${{secrets.GITHUB_TOKEN}} 

      

      # - name: Updaet repo Description
      #   uses: actions/github-script@v7
      #   with:
      #     script: |
      #        await github.rest.repos.update({
      #             owner: context.repo.owner,
      #             repo: context.repo.repo,
      #             description: "This is vinay testing description"
      #             });
      #   env:
      #    github-token: ${{secrets.GITHUB_TOKEN}}
