name: Checkout
on: [push]

jobs:
 
  checkout-and-display-files:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout
      #   id: gitcheckout
      #   run: |
      #      git init
      #      git config --global init.defaultBranch
      #      git checkout remote_branch
      #   env:
      #     GH_TOKEN: ${{ github.token }}
      - uses : actions/checkout@v4
        with :
          fetch-depth: 0
          
      - name: repodescription
        shell: bash
        run: |
          echo '{"description":"testing grep desc ≡ƒÜÇ"}' | grep -oP '(?<="description":")[^"]*'
        env:
          GH_TOKEN: ${{ github.token }}