name: Checkout
on: [push]

jobs:
 
  checkout-and-display-files:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout
      #   id: gitcheckout
      #   run: |
      #      git init
      #      git config --global init.defaultBranch
      #      git checkout remote_branch
      #   env:
      #     GH_TOKEN: ${{ github.token }}
      - uses : actions/checkout@v4
        with :
          fetch-depth: 0
          
      - name: repodescription
        shell: bash
        run: |
          gh repo view --json description | tee -a log.txt
          $ echo 'Here is a string, and Here is another string.' | grep -oP '(?<=Here).*?(?=string)' # Non-greedy match (Notice the '?' after '*' in .*)
          grep -oP '(?<=:).*?(?=})' # Non-greedy match (Notice the '?' after '*' in .*) | finallog.txt
          echo "repo-description=$(cat finallog.txt)" 
        env:
          GH_TOKEN: ${{ github.token }}