name: Checkout
on: [push]

jobs:
 
  checkout-and-display-files:
    runs-on: ubuntu-latest
    steps:
      - uses : actions/checkout@v4
        with :
          fetch-depth: 0
          
      - name: repodescription
        shell: bash
        run: |
          gh repo view --json description | grep -oP '(?<="description":")[^"]*' | grep -oP '[a-zA-Z0-9 ]+' | tee -a log.txt
          echo "repo-description=$(cat log.txt)" 
        env:
         GH_TOKEN: ${{secrets.GITHUB_TOKEN}} 

      - name: Updaet repo Description
        uses: actions/github-script@v7
        with:
          script: |
             await github.rest.repos.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  description: "This is vinay testing description"
                  });
        env:
         github-token:  ${{ secrets.GITHUB_TOKEN }}
