
name: Workflow Commands
on: [push]

jobs:
    testing-wf-commands:
         runs-on: ubuntu-latest
         steps:
            - name: Setting an error message
              run: echo "::error::Missing semicolon"
            - name: Setting an error message with params
              run: echo "::error title:Error title,file=app.js,line=2,
               lin=2,col=5,endLine"
            - name: Setting an debug message with params
              run: echo "::error title:debug title,file=app.js,line=2,
                lin=2,col=5,endLine"
            - name: Setting an Warning message with params
              run: echo "::error title:Warning title,file=app.js,line=2,
                 lin=2,col=5,endLine"
            - name: Setting an notice message with params
              run: echo "::error notice:Warning title,file=app.js,line=2,
                 lin=2,col=5,endLine"